server:
   port: 8796
   # Tomcat
   tomcat:
       uri-encoding: UTF-8
       max-threads: 1000
       min-spare-threads: 30
#   指定服务注册中心
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 服务名称
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  application:
    name: user-service
  redis:
    database: 0
    host: 106.12.101.177
    port: 6379
    password:     # 密码（默认为空）
    timeout: 2s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  #zipkin服务所在地址
  zipkin:
    base-url: http://106.12.101.177:9411/   #后期 部署改为内网ip
#配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1
  # 环境 sit:集成测试环境|pre:预生产环境|prd:生成环境
  profiles:
    active: dev

jwt:
  header: token
logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
  path: concretepage/logs

# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath*:mapper/*Mapper.xml


