server:
   port: 8781
#   指定服务注册中心
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true #开启feign支持hystrix  (注意，一定要开启，旧版本默认支持，新版本默认关闭)
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000 #超时时间
spring:
  application:
      name: order-service
  redis:
    database: 0
    host: 106.12.101.177
    port: 6379
    password:     # 密码（默认为空）
    timeout: 2s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
