server:
  port: 8099

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


file:
  download_path: /downloads

spring:
  application:
    name: video-service
  redis:
    database: 0
    host: jinghan.club
    port: 6379
    password:     # 密码（默认为空）
    timeout: 2s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
