

# Tomcat
server:
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
  port: 8796
#   指定服务注册中心
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
# 服务名称
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  application:
    name: user-service
  # 环境 sit:集成测试环境|pre:预生产环境|prd:生成环境
  profiles:
    active: dev

jwt:
  header: token
  tokenHead: Bearer
# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath*:com/yf/**/mapper/*Mapper.xml

