server:
   port: 8791
#   指定服务注册中心
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
# 服务名称
spring:
  application:
    name: user-service
  profiles:
    active: prd
jwt:
  tokenHeader: token
  tokenHead: Bearer
