

spring:
  profiles :  peerl
  application :
  name :  eureka-server-peer

eureka:
  instance:
      hostname: peer1
  client:
         #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，
        # 不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetch-registry: false
    register-with-eureka: false # 由于当前这个应用就是Eureka Server，故而设为false
    serviceUrl:
        defaultZone: http://localhost:8762/eureka/







